### PR TITLE
add missing properties to repository builders (#260)

### PR DESCRIPTION
**Pull request by dodie**

### CODE REVIEW

**Comment by eyalbe4** [comment]
recheckcla

**Comment by eyalbe4** [comment]
@dodie,
Would you like to continue promoting this PR?

**Comment by dodie** [comment]
If possible, yes. Do I need to do anything in addition to accept the CLA? Is the CLA need to be accepted for each individual contribution?

**Comment by eyalbe4** [comment]
Just signing the CLA @dodie.
Please ignore the comment added by **CLAassistant** on June (because it is no longer in use), and follow the request in the comment added by the **github-actions bit** 8 days ago.
Thank you!

**Comment by dodie** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
