### PR TITLE
Support limit and offset in AqlQueryBuilder

### PR DESCRIPTION
**Pull request by sailingcat**
- [x] All [tests](https://github.com/jfrog/artifactory-client-java#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
-----

### CODE REVIEW

**Comment by sailingcat** [comment]
Includes limit (Done in https://github.com/jfrog/artifactory-client-java/pull/294).

**Comment by sailingcat** [comment]
@eyalbe4 Could you please review my PR please ?

**Review by yahavi — APPROVED** [review]
Thanks, @sailingcat!

**Comment by yahavi** [comment]
Hey @sailingcat,
The latest release of Artifactory Java client, version 2.17.0, is now available. This update incorporates the changes mentioned in https://github.com/jfrog/artifactory-client-java/pull/371 & https://github.com/jfrog/artifactory-client-java/pull/370, which you contributed. Please consider upgrading, and your feedback would be greatly valued.

**Pull request merged**
