### PR TITLE
Remove compile dependency upon logback-clasic

### LINKED ISSUE #43: Dependency on ch.qos.logback:logback-classic:1.0.9
Please remove the compile dependency on ch.qos.logback:logback-classic jar file.

A work around is for the user to create a logback.xml file to block debug level messages before moving to production, but slf4j has better solutions.

### LINKED ISSUE #232: Library shouldn't depend upon logback-core
The published library has an explicit dependency on logback-core.

This defeats the purpose of SLF4J. SLF4J is supposed to be a logging facade that allows the application using the libraries to choose the logging implementation.

I've run into this issue when including this library in a Gradle Plugin. Because this library depends on logback-core, it clashes with Gradle's built-in SLF4J implementation.

https://github.com/jfrog/artifactory-client-java/blob/ee01570aa80cc72fc3ad033f771702299a0afe24/services/build.gradle#L14

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Closes #232
Closes #43

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Ping.

**Comment by eyalbe4** [comment]
Thanks you for this @JLLeitschuh.
We'll get to merging this soon.

**Comment by eyalbe4** [comment]
@JLLeitschuh - sorry for the late response here!
Can you please join our contributors community by signing [JFrog's CLA](https://secure.echosign.com/public/hostedForm?formid=5IYKLZ2RXB543N) so that we can merge your code?

**Comment by JLLeitschuh** [comment]
When I open the CLA form, the contents aren't loading.

Screen Shot 2019-03-14 at 11 50 53 AM

I've tried this with both Firefox and Chrome.

**Comment by eyalbe4** [comment]
Thanks for letting us know @JLLeitschuh.
We're checking this now.

**Comment by JLLeitschuh** [comment]
Signed.

**Comment by JLLeitschuh** [comment]
Ping!

**Pull request merged**
