### PR TITLE
Update depencies

### PR DESCRIPTION
**Pull request by julienje**
Update some depencies and adapt code when needed

### CODE REVIEW

**Comment by julienje** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by eyalbe4** [comment]
Thanks foe this contribution @julienje!
See the above message from the CLA Assistant bot. The fact that your signature hasn't been accepted may be related to your email configuration.

**Comment by eyalbe4** [comment]
recheckcla

**Comment by julienje** [comment]
I will open a new one with a correct git config

**Pull request closed without merging**
