### PR TITLE
Upgrade groovy from 2.4.21 to 4.0.23

### PR DESCRIPTION
**Pull request by j-sandy**
- [ ] All [tests](https://github.com/jfrog/artifactory-client-java#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
-----

### CODE REVIEW

**Comment by j-sandy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by j-sandy** [comment]
recheck

**Comment by yahavi** [comment]
@j-sandy  
Artifactory Java client version 2.19.1 has been released. This update includes the specified change.  
Feel free to reach out if you need any further assistance.

**Comment by jonesbusy** [comment]
This is a breaking change for consumers. There is not binary compatibility between major groovy version.

**Comment by jonesbusy** [comment]
Also because of the package change, consumer excluding dependency (because provided by other mean) will need to adapt.

This is clearly not a patch release but a breaking change

**Pull request merged**
