### PR TITLE
Upgrade gradle from 5.6.4 to 7.6.4

### PR DESCRIPTION
**Pull request by j-sandy**
- [x] All [tests](https://github.com/jfrog/artifactory-client-java#building-and-testing-the-sources) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is on the dev branch.
-----

### CODE REVIEW

**Comment by j-sandy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by j-sandy** [comment]
recheck

**Comment by yahavi** [comment]
@j-sandy - what is the reason for this change?

**Comment by j-sandy** [comment]
> @j-sandy - what is the reason for this change?

@yahavi  We are upgrading [Spinnaker](https://github.com/spinnaker/spinnaker), an open-source continuous delivery platform, to adopt groovy 4. This activity is part of a bigger mission to reduce the vulnerabilities and making Spinnaker secure. 
Jfrog artifactory java client is used as one of the [dependency](https://github.com/spinnaker/igor/blob/372f869d126bfc2080283db8ceb15a397003302d/igor-monitor-artifactory/igor-monitor-artifactory.gradle#L26) in a Spinnaker component, it bring groovy 2 as its transitive dependency, so in order to avoid exclusion of groovy from this package and to contribute back our experiences of groovy upgrades, we would like to upgrade the package to groovy 4.
And gradle upgrade is first step towards it.
Please suggest, if any, limitations in this approach.

**Comment by j-sandy** [comment]
@yahavi Should I raise PR to dev branch first for gradle upgrade ?

**Comment by yahavi** [comment]
@j-sandy 
I don't see any limitations for upgrading to Gradle 7. However, 7.6.1 is not the latest patch version. Would you like to upgrade to 7.6.4 instead?

**Comment by j-sandy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by j-sandy** [comment]
recheck

**Comment by j-sandy** [comment]
@yahavi Could you please help to initiate the build ? Or please let me know if I missed any requirement to proceed.

**Review by yahavi — APPROVED** [review]
Thanks, @j-sandy!

**Comment by yahavi** [comment]
@j-sandy  
Artifactory Java client version 2.19.0 has been released. This version was built using Gradle 7.6.4.
Let us know if it works for you!

**Comment by j-sandy** [comment]
Thanks @yahavi !
It is a useful improvement towards the final goal of groovy 4 upgrade. I will be raising another PR to upgrade groovy 2.x to 4.x.
Appreciate you kind support.

**Comment by j-sandy** [comment]
https://github.com/jfrog/artifactory-client-java/pull/394

**Pull request merged**
